<template>
  <div class="container">
    <div v-for="count in counts" :key="count">{{ arr }}</div>
  </div>
</template>

<script>
export default {
  props: {
    error: {
      type: Object,
      default: null,
    },
  },
  data() {
    return { arr: [], counts: [1, 2, 3, 4, 5] };
  },
  async fetch() {
    const fn = () => {
      return new Promise((resolve) => {
        resolve([
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
          "test",
        ]);
      });
    };
    const d = await fn();
    console.log(d);
    this.arr = d.concat([d, d, d, d, d, d, d, d, d, d, d, d, d, d, d, d, d]);
  },
};
</script>
